import './globals.css'
import Navbar from '../../components/navbar'

export const metadata = {
  title: 'Tongariro Cinemas',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="">
        <Navbar />
        {children}
      </body>
    </html>
  )
}
